# Generated by Django 3.0.8 on 2020-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_day', '0002_auto_20200819_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayweek',
            name='day',
            field=models.PositiveIntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')]),
        ),
    ]
