# Generated by Django 3.0.8 on 2020-08-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_day', '0009_auto_20200819_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayweek',
            name='day',
            field=models.PositiveIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
