# Generated by Django 3.0.8 on 2020-08-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day_day', '0010_auto_20200819_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routinecontent',
            old_name='priotiry',
            new_name='priority',
        ),
    ]
