# Generated by Django 3.0.8 on 2020-10-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_day', '0012_auto_20200924_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='type_TAA',
            field=models.CharField(default='Advice', max_length=25),
        ),
        migrations.AddField(
            model_name='appointment',
            name='type_TAA',
            field=models.CharField(default='Appointment', max_length=25),
        ),
        migrations.AddField(
            model_name='task',
            name='type_TAA',
            field=models.CharField(default='Task', max_length=25),
        ),
    ]
